/**
 * Single-source gate for the dual-encoder DATA (see
 * src/rl/docs/ENCODER_SINGLE_SOURCE_PROPOSAL.md, Phase 1).
 *
 * Serializes every table/constant the Python mirror needs from the LIVE TS
 * modules (the wire authority) into src/rl/generated/encoder-data.json and
 * asserts the checked-in artifact matches — so the generated data can never
 * go stale without failing the ordinary vitest gate (rl-verify V11 / CI).
 *
 * To regenerate after intentionally changing encoder tables:
 *
 *   UPDATE_RL_ENCODER_DATA=1 pnpm exec vitest run test/rl/encoder-data-sync.test.ts
 *
 * The Python side loads this JSON via src/rl/encoder_data.py; cross-language
 * equality of the ENCODERS (logic) is separately proven bitwise by the golden
 * fixtures + tools/verify/check_parity.py.
 */

import { Gender } from "#data/gender";
import { TerrainType } from "#data/terrain";
import { AiType } from "#enums/ai-type";
import { ArenaTagSide } from "#enums/arena-tag-side";
import { ArenaTagType } from "#enums/arena-tag-type";
import { BattleStyle } from "#enums/battle-style";
import { BattleType } from "#enums/battle-type";
import { BattlerIndex } from "#enums/battler-index";
import { BattlerTagType } from "#enums/battler-tag-type";
import { BerryType } from "#enums/berry-type";
import { Command } from "#enums/command";
import { GameModes } from "#enums/game-modes";
import { HitResult } from "#enums/hit-result";
import { ModifierTier } from "#enums/modifier-tier";
import { MoveCategory } from "#enums/move-category";
import { MoveResult } from "#enums/move-result";
import { MultiHitType } from "#enums/multi-hit-type";
import { Nature } from "#enums/nature";
import { PokeballType } from "#enums/pokeball";
import { PokemonType } from "#enums/pokemon-type";
import { Stat } from "#enums/stat";
import { StatusEffect } from "#enums/status-effect";
import { TimeOfDay } from "#enums/time-of-day";
import { WeatherType } from "#enums/weather-type";
import { ABILITY_FEATURES, FEATURE_DIM } from "#rl/ability-features";
import {
  DEFAULT_MODIFIER_FEATURES,
  MODIFIER_FEATURE_DIM,
  MODIFIER_FEATURES,
  PRIORITY_KEYS,
} from "#rl/modifier-features";
import * as spaces from "#rl/spaces";
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

const OUT_PATH = path.resolve(__dirname, "../../src/rl/generated/encoder-data.json");

/** Numeric-enum members as {NAME: value}, dropping TS reverse mappings. */
function numericEnum(e: Record<string, unknown>): Record<string, number> {
  const out: Record<string, number> = {};
  for (const [k, v] of Object.entries(e)) {
    if (typeof v === "number") {
      out[k] = v;
    }
  }
  return out;
}

/** String-enum members as {NAME: value}. */
function stringEnum(e: Record<string, unknown>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(e)) {
    if (typeof v === "string") {
      out[k] = v;
    }
  }
  return out;
}

function buildPayload(): Record<string, unknown> {
  return {
    _meta: {
      note: "GENERATED by test/rl/encoder-data-sync.test.ts from the live TS encoder modules — DO NOT EDIT. Regenerate: UPDATE_RL_ENCODER_DATA=1 pnpm exec vitest run test/rl/encoder-data-sync.test.ts",
      authority: "src/rl/spaces.ts + ability-features.ts + modifier-features.ts + src/enums/*",
    },
    dims: {
      OBSERVATION_DIM: spaces.OBSERVATION_DIM,
      POKEMON_BLOCK_DIM: spaces.POKEMON_BLOCK_DIM,
      MOVE_BLOCK_DIM: spaces.MOVE_BLOCK_DIM,
      FIELD_STATE_DIM: spaces.FIELD_STATE_DIM,
      BATTLE_META_DIM: spaces.BATTLE_META_DIM,
      MODIFIER_PHASE_DIM: spaces.MODIFIER_PHASE_DIM,
      MODIFIER_INVENTORY_DIM: spaces.MODIFIER_INVENTORY_DIM,
      DERIVED_FIELDS_DIM: spaces.DERIVED_FIELDS_DIM,
      LEARN_MOVE_BLOCK_DIM: spaces.LEARN_MOVE_BLOCK_DIM,
      PHASE_INDICATOR_DIM: spaces.PHASE_INDICATOR_DIM,
      REWARD_OPTION_DIM: spaces.REWARD_OPTION_DIM,
      SHOP_OPTION_DIM: spaces.SHOP_OPTION_DIM,
      HELD_ITEM_SLOT_DIM: spaces.HELD_ITEM_SLOT_DIM,
      MAX_HELD_ITEMS_ENCODED: spaces.MAX_HELD_ITEMS_ENCODED,
      ABILITY_FEATURE_DIM: FEATURE_DIM,
      MODIFIER_FEATURE_DIM,
    },
    caps: {
      NUM_POKEMON_TYPES: spaces.NUM_POKEMON_TYPES,
      NUM_STATUS_EFFECTS: spaces.NUM_STATUS_EFFECTS,
      NUM_WEATHER_TYPES: spaces.NUM_WEATHER_TYPES,
      NUM_TERRAIN_TYPES: spaces.NUM_TERRAIN_TYPES,
      NUM_ARENA_TAG_TYPES: spaces.NUM_ARENA_TAG_TYPES,
      NUM_MOVE_CATEGORIES: spaces.NUM_MOVE_CATEGORIES,
      NUM_BATTLE_TYPES: spaces.NUM_BATTLE_TYPES,
      NUM_MODIFIER_TIERS: spaces.NUM_MODIFIER_TIERS,
      NUM_POKEBALL_TYPES: spaces.NUM_POKEBALL_TYPES,
      NUM_CURATED_TAGS: spaces.NUM_CURATED_TAGS,
      MAX_MOVES: spaces.MAX_MOVES,
      MAX_PARTY_SIZE: spaces.MAX_PARTY_SIZE,
      MAX_ACTIVE_PER_SIDE: spaces.MAX_ACTIVE_PER_SIDE,
      MAX_BENCH_SIZE: spaces.MAX_BENCH_SIZE,
      TOTAL_POKEMON_SLOTS: spaces.TOTAL_POKEMON_SLOTS,
      MAX_REWARD_OPTIONS: spaces.MAX_REWARD_OPTIONS,
      MAX_SHOP_OPTIONS: spaces.MAX_SHOP_OPTIONS,
      MAX_SHOP_OPTIONS_ENCODED: spaces.MAX_SHOP_OPTIONS_ENCODED,
    },
    action_space: {
      ACTION_SPACE_SIZE: spaces.ACTION_SPACE_SIZE,
      ACTION_FIGHT_ENEMY_START: spaces.ACTION_FIGHT_ENEMY_START,
      ACTION_FIGHT_ENEMY2_START: spaces.ACTION_FIGHT_ENEMY2_START,
      ACTION_FIGHT_ALLY_START: spaces.ACTION_FIGHT_ALLY_START,
      ACTION_SWITCH_START: spaces.ACTION_SWITCH_START,
      ACTION_BALL_START: spaces.ACTION_BALL_START,
      ACTION_RUN: spaces.ACTION_RUN,
      ACTION_TERA_ENEMY_START: spaces.ACTION_TERA_ENEMY_START,
      ACTION_TERA_ENEMY2_START: spaces.ACTION_TERA_ENEMY2_START,
      ACTION_TERA_ALLY_START: spaces.ACTION_TERA_ALLY_START,
      ACTION_SELECT_REWARD_START: spaces.ACTION_SELECT_REWARD_START,
      ACTION_REROLL: spaces.ACTION_REROLL,
      ACTION_SKIP: spaces.ACTION_SKIP,
      ACTION_BUY_SHOP_START: spaces.ACTION_BUY_SHOP_START,
      ACTION_PARTY_TARGET_START: spaces.ACTION_PARTY_TARGET_START,
    },
    // Top-level block layout in ENCODER WRITE ORDER (encodeObservation):
    // 12 pokemon slots, then field/battle/modifier/inventory/derived/
    // learn-move/phase. feature_names.BLOCK_RANGES must match exactly
    // (checked by tools/verify/check_generated_sync.py).
    block_layout: (() => {
      const blocks: [string, number][] = [
        ...spaces.POKEMON_SLOT_KEYS.map((k): [string, number] => [k, spaces.POKEMON_BLOCK_DIM]),
        ["field", spaces.FIELD_STATE_DIM],
        ["battle", spaces.BATTLE_META_DIM],
        ["modifier_phase", spaces.MODIFIER_PHASE_DIM],
        ["modifier_inventory", spaces.MODIFIER_INVENTORY_DIM],
        ["derived", spaces.DERIVED_FIELDS_DIM],
        ["learn_move", spaces.LEARN_MOVE_BLOCK_DIM],
        ["phase_indicator", spaces.PHASE_INDICATOR_DIM],
      ];
      let base = 0;
      return blocks.map(([name, dim]) => {
        const entry = { name, base, dim };
        base += dim;
        return entry;
      });
    })(),
    phase_index_map: spaces.PHASE_INDEX_MAP,
    curated_volatile_tags: spaces.CURATED_VOLATILE_TAGS,
    arena_tag_order: spaces.ARENA_TAG_ORDER,
    key_arena_tags: spaces.KEY_ARENA_TAGS,
    self_ally_targets: [...spaces.SELF_ALLY_TARGETS].sort((a, b) => a - b),
    single_enemy_targets: [...spaces.SINGLE_ENEMY_TARGETS].sort((a, b) => a - b),
    other_effect_flags: spaces.OTHER_EFFECT_FLAGS,
    type_effectiveness: spaces.TYPE_EFFECTIVENESS,
    stage_multipliers: spaces.STAGE_MULTIPLIERS,
    pokemon_slot_keys: spaces.POKEMON_SLOT_KEYS,
    active_slot_keys: spaces.ACTIVE_SLOT_KEYS,
    pokeball_keys: spaces.POKEBALL_KEYS,
    party_flag_ids: spaces.PARTY_FLAG_IDS,
    enemy_mod_ids: spaces.ENEMY_MOD_IDS,
    enemy_mod_norm_divisors: spaces.ENEMY_MOD_NORM_DIVISORS,
    modifier_priority_keys: PRIORITY_KEYS,
    ability_features: ABILITY_FEATURES.map(row => Array.from(row)),
    modifier_features: Object.fromEntries(Object.entries(MODIFIER_FEATURES).map(([id, vec]) => [id, Array.from(vec)])),
    default_modifier_features: Array.from(DEFAULT_MODIFIER_FEATURES),
    enums: {
      PokemonType: numericEnum(PokemonType),
      StatusEffect: numericEnum(StatusEffect),
      WeatherType: numericEnum(WeatherType),
      TerrainType: numericEnum(TerrainType),
      MoveCategory: numericEnum(MoveCategory),
      Nature: numericEnum(Nature),
      Gender: numericEnum(Gender),
      BattleType: numericEnum(BattleType),
      ModifierTier: numericEnum(ModifierTier),
      PokeballType: numericEnum(PokeballType),
      AiType: numericEnum(AiType),
      Stat: numericEnum(Stat),
      MultiHitType: numericEnum(MultiHitType),
      ArenaTagSide: numericEnum(ArenaTagSide),
      BattlerIndex: numericEnum(BattlerIndex),
      GameModes: numericEnum(GameModes),
      TimeOfDay: numericEnum(TimeOfDay),
      BattleStyle: numericEnum(BattleStyle),
      BerryType: numericEnum(BerryType),
      HitResult: numericEnum(HitResult),
      MoveResult: numericEnum(MoveResult),
      Command: numericEnum(Command),
    },
    string_enums: {
      BattlerTagType: stringEnum(BattlerTagType),
      ArenaTagType: stringEnum(ArenaTagType),
    },
  };
}

describe("encoder-data single-source gate", () => {
  it("checked-in generated/encoder-data.json matches the live TS modules", () => {
    const payload = buildPayload();
    const rendered = `${JSON.stringify(payload, null, 2)}\n`;

    if (process.env.UPDATE_RL_ENCODER_DATA) {
      fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
      fs.writeFileSync(OUT_PATH, rendered);
      console.log(`regenerated ${OUT_PATH}`);
      return;
    }

    expect(fs.existsSync(OUT_PATH), `missing ${OUT_PATH} — regenerate with UPDATE_RL_ENCODER_DATA=1`).toBe(true);
    const checkedIn = fs.readFileSync(OUT_PATH, "utf8");
    expect(checkedIn, "generated encoder-data.json is STALE — regenerate with UPDATE_RL_ENCODER_DATA=1").toBe(rendered);
  });

  it("payload sanity: table shapes match the declared dims", () => {
    const payload = buildPayload() as Record<string, any>;
    expect(payload.ability_features).toHaveLength(311);
    for (const row of payload.ability_features) {
      expect(row).toHaveLength(FEATURE_DIM);
    }
    for (const vec of Object.values(payload.modifier_features) as number[][]) {
      expect(vec).toHaveLength(MODIFIER_FEATURE_DIM);
    }
    expect(payload.type_effectiveness).toHaveLength(spaces.NUM_POKEMON_TYPES);
    expect(payload.curated_volatile_tags).toHaveLength(spaces.NUM_CURATED_TAGS);
    expect(payload.arena_tag_order).toHaveLength(spaces.NUM_ARENA_TAG_TYPES);
    expect(payload.stage_multipliers).toHaveLength(13);
    // block layout must tile [0, OBSERVATION_DIM) exactly
    const blocks = payload.block_layout as { name: string; base: number; dim: number }[];
    const end = blocks.reduce((pos, b) => {
      expect(b.base).toBe(pos);
      return pos + b.dim;
    }, 0);
    expect(end).toBe(spaces.OBSERVATION_DIM);
  });
});
